name: 'Datadog holiday service check action'
description: 'Create datadog service check from date list'
author: 'Yutachaos'
inputs:
  holidays:
    description: 'Holiday list'
    required: true
  service_check_name:
    description: 'Datadog servicecheck name'
    required: true
  host_name:
    description: 'Datadog servicecheck host name'
    required: true
  tags:
    description: 'Datadog servicecheck check tags'
    required: false
outputs:
  is_holiday:
    description: 'Is holiday'
runs:
  using: 'node16'
  main: 'dist/index.js'
